### ISSUE TITLE
Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by SushyDev** [DanielRamosAcosta/jdownloader-client#1]
VM955:75 TypeError: Cannot read property 'join' of undefined
    at JDownloaderClient.linkGrabberAddLinks (jdownloader-client.ts:77)

const addlink = await client.linkGrabberAddLinks(devices[0].id, "https://download.link/file.zip")

**Comment by DanielRamosAcosta** [comment]
@CrypticShy the second parameter of the [linkGrabberAddLinks](https://www.danielramos.me/jdownloader-client/classes/jdownloaderclient.html#linkgrabberaddlinks) method isn't a link, it's an [options object](https://www.danielramos.me/jdownloader-client/interfaces/iaddlinksquery.html)

Try this:

```ts
const addLinks = await client.linkGrabberAddLinks(devices[0].id, {
  links: [
    "https://file-examples.com/wp-content/uploads/2017/02/zip_5MB.zip"
  ]
})

console.log(addLinks)
```
